#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail() { echo "qml.test: $*" >&2; exit 1; }

grep -q 'id: afterPeakMonitor' "$root/Panel.qml" || fail "Panel needs afterPeakMonitor"
grep -q 'id: rowPeak' "$root/Panel.qml" || fail "each mic row needs a peak monitor"
grep -q 'PwNodePeakMonitor' "$root/Panel.qml" || fail "Panel must use PwNodePeakMonitor"
grep -q 'afterPeakMonitor.peak' "$root/Panel.qml" || fail "selected row must show After"
grep -q 'enabled: root.opened && root.metersArmed && !!node' "$root/Panel.qml" || fail "row meters must rebind after graph changes"
grep -q 'onAfterNodeNameChanged: syncMeterHold' "$root/Service.qml" || fail "hold must wait for the bound Omavoice name"
grep -q 'id: meterHoldWatch' "$root/Service.qml" || fail "hold must retry if it never started"
grep -q 'startDebounce' "$root/Service.qml" || fail "preset switches must debounce the host restart"
grep -q 'shouldDeferSourcePick' "$root/Service.qml" || fail "source pick must ignore unbound-name flicker"
grep -q 'Util.alpha' "$root/Panel.qml" || fail "meters must use Omarchy audio chrome"
grep -q 'setMeterHold' "$root/Service.qml" || fail "Service must expose setMeterHold"
grep -q 'pw-cat' "$root/Service.qml" || fail "Service must hold the graph with pw-cat"
grep -q '"--target", name' "$root/Service.qml" || fail "pw-cat must target the bound omavoice name"
grep -q '"--target", nodeId' "$root/Service.qml" && fail "pw-cat must not target Quickshell node ids"
grep -q 'node.dont-fallback=true' "$root/Service.qml" && fail "pw-cat dont-fallback prevents the meter hold from attaching"
grep -q '/dev/null' "$root/Service.qml" || fail "meter hold must discard audio"
grep -q 'afterNodeName' "$root/Service.qml" || fail "Service must expose the bound afterNodeName"
grep -q 'afterNode' "$root/Service.qml" || fail "Service must expose afterNode"
grep -q 'nodeNamed' "$root/Service.qml" || fail "Service must look up capture nodes by name"
grep -q '"version": "0.2.0-dev"' "$root/manifest.json" || fail "manifest must be 0.2.0-dev"
[[ -f "$root/preview.png" ]] || fail "marketplace needs root preview.png"
[[ -f "$root/docs/preview-tune.png" ]] || fail "preset tune screenshot must be in docs"
grep -q 'id: reloadButton' "$root/Panel.qml" || fail "header needs a reload next to on/off"
grep -q 'iconText: service.reloading ? "󰑓" : "󰑐"' "$root/Panel.qml" || fail "reload must use the HEY/Fizzy refresh icons"
grep -q 'function reload' "$root/Service.qml" || fail "Service must expose reload"
grep -q 'libdeep_filter_ladspa-bin' "$root/README.md" || fail "Podcast AUR package must be libdeep_filter_ladspa-bin"
grep -q 'deepfilternet-ladspa' "$root/README.md" && fail "deepfilternet-ladspa is not an AUR package"
grep -q 'mktemp' "$root/scripts/omavoice-run" || fail "--dump must write a temp conf, not the live host"
grep -q '!n.isSink && !n.isStream' "$root/Service.qml" || fail "tracker must bind sources only"
grep -q 'onNodesChanged: refreshSources' "$root/Service.qml" || fail "sources must refresh on PipeWire node changes"
grep -q 'plugins.omarchy.org' "$root/README.md" || fail "README must point at the official marketplace"
grep -q 'omarchyplugins.com' "$root/README.md" && fail "README must not use omarchyplugins.com"
[[ -e "$root/omavoice.png" ]] && fail "root omavoice.png leftover orb must be gone"
grep -q 'microphone.svg' "$root/OmavoiceIcon.qml" || fail "icon must use the microphone SVG"
grep -q 'docs/omavoice.svg' "$root/README.md" || fail "README must use the microphone banner"
grep -q 'Softer' "$root/Panel.qml" || fail "quality stops must be Softer / Balanced / Stronger"
grep -q 'qualityHint' "$root/Panel.qml" || fail "quality slider must explain the impact"
grep -q 'Your voice, better heard' "$root/README.md" || fail "README must keep the tagline"
grep -q 'component QualitySlider' "$root/Panel.qml" || fail "settings need a 3-stop quality slider"
grep -q 'meetingQuality' "$root/Service.qml" || fail "Service must expose meetingQuality"
grep -q '"--quality"' "$root/Service.qml" || fail "host must pass --quality"
grep -q '"--engine"' "$root/Service.qml" || fail "host must pass --engine"
grep -q '"--capture-gain-db"' "$root/Service.qml" || fail "host must bake capture gain"
grep -q '"--output-gain-db"' "$root/Service.qml" || fail "host must bake output gain"
grep -q 'omavoice-ctl' "$root/Service.qml" || fail "live controls must use omavoice-ctl"
grep -q 'function setEngine' "$root/Panel.qml" || fail "tune page must set engine"
grep -q 'function setOutputGainDb' "$root/Panel.qml" || fail "Panel must persist output gain"
grep -q 'function setCaptureGainDb' "$root/Panel.qml" || fail "Panel must persist capture gain"
grep -q 'property bool levelOpen' "$root/Panel.qml" || fail "Level drawer must start collapsed"
grep -q 'text: "Level"' "$root/Panel.qml" || fail "Level chevron needs a hover tip"
grep -q 'font.bold: true' "$root/Panel.qml" && grep -B8 'text: "Level"' "$root/Panel.qml" | grep -q 'font.bold: true' && fail "Level must not be a word on the mic row"
grep -q 'title: "Output"' "$root/Panel.qml" || fail "Level drawer must label Output"
grep -q 'title: "Input"' "$root/Panel.qml" || fail "Level drawer must label Input"
grep -q 'property real held' "$root/Panel.qml" || fail "GainRow must hold the snapped value so the knob stays"
grep -q 'engineChoiceHint' "$root/Panel.qml" || fail "engine chips need hover tips"
grep -q 'engineSetting === "auto" && service.engine === modelData.value' "$root/Panel.qml" || fail "live-engine dot only when Auto is picked"
grep -q 'engineUsingLine' "$root/Panel.qml" && fail "do not print Using … under the engine chips"
grep -q 'levelOpen ? 90 : 180' "$root/Panel.qml" || fail "Level chevron must point left closed, down open"
grep -q 'snapGainDb' "$root/Panel.qml" || fail "faders must snap to 0.5 dB"
grep -q 'function snapGainDb' "$root/Model.js" || fail "snapGainDb lives in Model"
grep -q 'function previewGains' "$root/Service.qml" || fail "drag must preview gains without persist"
grep -q 'function clearGainPreview' "$root/Service.qml" || fail "release must clear gain preview"
grep -q 'Level into noise suppression' "$root/Panel.qml" && fail "NS caption must be gone"
grep -q 'text: "Out"' "$root/Panel.qml" && fail "Out shorthand must be gone"
grep -q 'text: "In"' "$root/Panel.qml" && fail "In shorthand must be gone"
grep -q 'meetingOutputGainDb' "$root/manifest.json" || fail "schema needs meetingOutputGainDb"
grep -q 'podcastOutputGainDb' "$root/manifest.json" || fail "schema needs podcastOutputGainDb"
grep -q 'cleanOutputGainDb' "$root/manifest.json" || fail "schema needs cleanOutputGainDb"
grep -q 'meetingCaptureGainDb' "$root/manifest.json" || fail "schema needs meetingCaptureGainDb"
grep -q 'podcastCaptureGainDb' "$root/manifest.json" || fail "schema needs podcastCaptureGainDb"
grep -q 'cleanCaptureGainDb' "$root/manifest.json" || fail "schema needs cleanCaptureGainDb"
grep -q 'preset + "\\0" + engine + "\\0" + targetName' "$root/Service.qml" || fail "hostKey must include engine"
grep -q 'preset + "\\0" + quality + "\\0"' "$root/Service.qml" && fail "hostKey must not include quality"
grep -q 'onQualityChanged: applyLiveControls' "$root/Service.qml" || fail "quality must apply live"
grep -q 'onOutputGainDbChanged: applyLiveControls' "$root/Service.qml" || fail "output gain must apply live"
grep -q 'onCaptureGainDbChanged: applyLiveControls' "$root/Service.qml" || fail "capture gain must apply live"
grep -q 'gainPreview ? previewCaptureDb : captureGainDb' "$root/Service.qml" || fail "preview must override capture while dragging"
grep -q 'gainPreview ? previewOutputDb : outputGainDb' "$root/Service.qml" || fail "preview must override output while dragging"
grep -q 'onPresetChanged: syncHost' "$root/Service.qml" || fail "preset must restart the host"
grep -q 'onEngineChanged: syncHost' "$root/Service.qml" || fail "engine must restart the host"
grep -q 'id: heroIcon' "$root/Panel.qml" || fail "header must use the Omavoice mark"
grep -q 'id: powerSwitch' "$root/Panel.qml" || fail "on/off must be the original pill toggle"
grep -q 'id: powerButton' "$root/Panel.qml" && fail "power icon button must be gone"
grep -q 'function showTune' "$root/Panel.qml" || fail "preset settings must flip to a tune page"
grep -q 'id: presetTuneButton' "$root/Panel.qml" || fail "PRESET needs a settings action"
grep -q 'iconText: "󰒓"' "$root/Panel.qml" || fail "preset tuning must use a settings icon"
grep -q 'text: "AUTOMATIC"' "$root/Panel.qml" || fail "MICROPHONE must use the network AUTOMATIC toggle"
grep -q 'id: pageFlip' "$root/Panel.qml" || fail "tune page must animate like HEY"
grep -q 'label: "Default microphone"' "$root/Panel.qml" && fail "default mic must not live on a settings dump"
grep -q 'viewBox="0 0 24 24"' "$root/microphone.svg" || fail "microphone.svg must be the square mic mark"
grep -q 'the record button' "$root/README.md" && fail "README must not talk about a record button"

grep -q 'setListen' "$root/Service.qml" && fail "Listen must be gone from Service"
grep -q 'listenProcess' "$root/Service.qml" && fail "Listen process must be gone"
grep -q 'pw-loopback' "$root/Service.qml" && fail "pw-loopback must be gone"
grep -q 'toggleListen' "$root/Panel.qml" && fail "Listen must be gone from Panel"
grep -q 'Listen (use headphones)' "$root/Panel.qml" && fail "Listen row must be gone"
grep -q 'id: beforePeakMonitor' "$root/Panel.qml" && fail "hero Before/After meters must be gone"
grep -q 'label: "Before"' "$root/Panel.qml" && fail "hero Before bar must be gone"

echo "qml.test: ok"
