#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fail() { echo "qml.test: $*" >&2; exit 1; }

grep -q 'id: afterPeakMonitor' "$root/Panel.qml" || fail "Panel needs afterPeakMonitor"
grep -q 'id: rowPeak' "$root/Panel.qml" || fail "each mic row needs a peak monitor"
grep -q 'PwNodePeakMonitor' "$root/Panel.qml" || fail "Panel must use PwNodePeakMonitor"
grep -q 'afterPeakMonitor.peak' "$root/Panel.qml" || fail "selected row must show After"
grep -q 'enabled: root.opened && root.metersArmed && !!node' "$root/Panel.qml" || fail "row meters must rebind after graph changes"
grep -q 'onAfterNodeChanged: syncMeterHold' "$root/Service.qml" || fail "hold must wait for the Omavoice node"
grep -q 'node.dont-fallback=true' "$root/Service.qml" || fail "pw-cat must not fall back to another mic"
grep -q 'startDebounce' "$root/Service.qml" || fail "preset switches must debounce the host restart"
grep -q 'shouldDeferSourcePick' "$root/Service.qml" || fail "source pick must ignore unbound-name flicker"
grep -q 'Util.alpha' "$root/Panel.qml" || fail "meters must use Omarchy audio chrome"
grep -q 'setMeterHold' "$root/Service.qml" || fail "Service must expose setMeterHold"
grep -q 'pw-cat' "$root/Service.qml" || fail "Service must hold the graph with pw-cat"
grep -q '"--target", Model.NODE_NAME' "$root/Service.qml" || fail "pw-cat must target omavoice"
grep -q '/dev/null' "$root/Service.qml" || fail "meter hold must discard audio"
grep -q 'afterNode' "$root/Service.qml" || fail "Service must expose afterNode"
grep -q 'nodeNamed' "$root/Service.qml" || fail "Service must look up capture nodes by name"
grep -q '"version": "0.1.12"' "$root/manifest.json" || fail "manifest must be 0.1.12"
grep -q 'Softer' "$root/Panel.qml" || fail "quality stops must be Softer / Balanced / Stronger"
grep -q 'qualityHint' "$root/Panel.qml" || fail "quality slider must explain the impact"
grep -q 'id="wave"' "$root/microphone.svg" || fail "icon must be the wave orb"
grep -q 'component QualitySlider' "$root/Panel.qml" || fail "settings need a 3-stop quality slider"
grep -q 'meetingQuality' "$root/Service.qml" || fail "Service must expose meetingQuality"
grep -q '"--quality"' "$root/Service.qml" || fail "host must pass --quality"
grep -q 'id: heroIcon' "$root/Panel.qml" || fail "header must use the Omavoice mark"
grep -q 'id: powerSwitch' "$root/Panel.qml" || fail "on/off must be the original pill toggle"
grep -q 'bordered: true' "$root/Panel.qml" || fail "settings must share chrome with the toggle"
grep -q 'id: powerButton' "$root/Panel.qml" && fail "power icon button must be gone"
grep -q 'function showSettings' "$root/Panel.qml" || fail "Panel needs a settings flip"
grep -q 'id: pageFlip' "$root/Panel.qml" || fail "settings must animate like HEY"
grep -q 'label: "Default microphone"' "$root/Panel.qml" || fail "settings must expose default microphone"
grep -q 'Your voice, better heard' "$root/docs/omavoice.svg" || fail "banner must use the new tagline"
grep -q 'the record button' "$root/README.md" && fail "README must not talk about a record button"

grep -q 'setListen' "$root/Service.qml" && fail "Listen must be gone from Service"
grep -q 'listenProcess' "$root/Service.qml" && fail "Listen process must be gone"
grep -q 'pw-loopback' "$root/Service.qml" && fail "pw-loopback must be gone"
grep -q 'toggleListen' "$root/Panel.qml" && fail "Listen must be gone from Panel"
grep -q 'Listen (use headphones)' "$root/Panel.qml" && fail "Listen row must be gone"
grep -q 'id: beforePeakMonitor' "$root/Panel.qml" && fail "hero Before/After meters must be gone"
grep -q 'label: "Before"' "$root/Panel.qml" && fail "hero Before bar must be gone"

echo "qml.test: ok"
